#!/usr/bin/env bash
#
# Argos installer and updater for Debian-based Linux with systemd.
#
#   sudo mkdir -p /opt/argos && cd /opt/argos
#   curl -fsSL https://raw.githubusercontent.com/nexus421/Argos/main/scripts/install.sh | sudo bash
#
# or, with the script on disk:  sudo ./install.sh [--user NAME]
#
# Installs into the CURRENT directory: downloads argos.jar from the latest GitHub release,
# writes /etc/systemd/system/argos.service (WorkingDirectory = this directory, User = the
# user who invoked sudo unless --user is given), enables and (re)starts the service and
# writes a README.md with the operating instructions. Running it again updates Argos;
# config.json and data/ are never modified, the previous jar is kept as argos.jar.old.
#
# All checks run before anything is changed. The work happens in main(), which is called
# on the last line only, so a truncated download piped into bash executes nothing.

set -euo pipefail

readonly REPO="nexus421/Argos"
readonly LATEST_ASSET_URL="https://github.com/${REPO}/releases/latest/download/argos.jar"
readonly INSTALL_SCRIPT_URL="https://raw.githubusercontent.com/${REPO}/main/scripts/install.sh"
readonly UNIT_NAME="argos.service"
readonly UNIT_PATH="/etc/systemd/system/${UNIT_NAME}"
readonly MIN_JAVA_MAJOR=25
readonly README_MARKER="generated by Argos install.sh"
readonly CURL_OPTS=(--proto '=https' --proto-redir '=https' --tlsv1.2 -fsS --connect-timeout 15 --retry 3 --retry-delay 2)

TMP_JAR=""

log() { printf '%s\n' "$*"; }
die() { printf 'ERROR: %s\n' "$*" >&2; exit 1; }

cleanup() {
  if [[ -n $TMP_JAR ]]; then rm -f -- "$TMP_JAR"; fi
}

usage() {
  cat <<EOF
Argos installer / updater (Debian-based Linux with systemd)

Usage:  sudo ./install.sh [--user NAME]
        curl -fsSL ${INSTALL_SCRIPT_URL} | sudo bash [-s -- --user NAME]

Installs Argos into the CURRENT directory: downloads the latest release jar from
github.com/${REPO}, writes ${UNIT_PATH}, enables and
(re)starts the service and writes a README.md with the operating instructions.
Running it again in the same directory updates Argos; config.json and data/ are
never modified.

Options:
  --user NAME   run the service as NAME (default: the user who invoked sudo, else root)
  -h, --help    show this help
EOF
}

# ---------------------------------------------------------------------------
# Pure helpers (no side effects)
# ---------------------------------------------------------------------------

# Prints the major version found in the first line of `java -version` output, 0 if unparseable.
# "openjdk version \"25.0.1\"" -> 25, "java version \"1.8.0_392\"" -> 1.
java_major_version() {
  local first_line major
  first_line=${1%%$'\n'*}
  major=$(printf '%s' "$first_line" | sed -n 's/.*version "\([0-9][0-9]*\).*/\1/p')
  printf '%s' "${major:-0}"
}

# GitHub answers releases/latest/download/argos.jar with a redirect to
# releases/download/<tag>/argos.jar. Prints <tag>; fails on any other redirect target
# (captive portal, proxy, changed GitHub layout).
release_tag_from_redirect() {
  local url=$1 prefix="https://github.com/${REPO}/releases/download/" tag
  [[ $url == "${prefix}"*/argos.jar ]] || return 1
  tag=${url#"$prefix"}
  tag=${tag%/argos.jar}
  [[ $tag =~ ^[A-Za-z0-9._-]+$ ]] || return 1
  printf '%s' "$tag"
}

# Unit values are written unquoted: allow only characters systemd takes literally
# (no whitespace, quotes, backslashes, '%' specifiers, ...).
is_safe_for_unit() {
  [[ $1 =~ ^[A-Za-z0-9._/@:+-]+$ ]]
}

# Directories where installing would clutter the system or vanish on reboot.
is_forbidden_dir() {
  local dir=$1
  if [[ $dir =~ ^/home/[^/]+$ ]]; then return 0; fi
  case $dir in
    /|/root|/home|/usr|/bin|/sbin|/lib|/lib64|/usr/bin|/usr/sbin|/usr/lib|/usr/local) return 0 ;;
    /etc|/etc/*|/boot|/boot/*) return 0 ;;
    /opt|/srv|/var|/var/lib|/var/local|/mnt|/media) return 0 ;;
    /tmp|/tmp/*|/var/tmp|/var/tmp/*|/dev|/dev/*|/proc|/proc/*|/sys|/sys/*|/run|/run/*) return 0 ;;
  esac
  return 1
}

render_unit() {
  local dir=$1 user=$2 java=$3
  cat <<EOF
[Unit]
Description=Argos Monitoring
After=network-online.target
Wants=network-online.target

[Service]
Type=simple
User=${user}
WorkingDirectory=${dir}
# --enable-native-access: sqlite-jdbc loads native code; JDK 25 warns, later JDKs refuse without it
# -Xmx256m: plenty for Argos, prevents the JVM from claiming 1/4 of the host RAM
ExecStart=${java} --enable-native-access=ALL-UNNAMED -Xmx256m -jar ${dir}/argos.jar configPath=${dir}/config.json
Restart=always
RestartSec=5

[Install]
WantedBy=multi-user.target
EOF
}

render_readme() {
  local dir=$1 user=$2 version=$3 date=$4 java=$5 text
  # Quoted heredoc: backticks and $ stay literal; placeholders are substituted below.
  text=$(cat <<'EOF'
<!-- @MARKER@ on @DATE@. Rewritten on every run of install.sh - do not edit. -->
# Argos - installation notes

| | |
|---|---|
| Installed version | `@VERSION@` (installed @DATE@) |
| Install directory | `@DIR@` |
| Service user | `@USER@` |
| Java | `@JAVA@` |
| systemd unit | `/etc/systemd/system/argos.service` |
| Source | https://github.com/@REPO@ |

## Files in this directory

| File | Purpose |
|---|---|
| `argos.jar` | The application, release `@VERSION@`. |
| `argos.jar.old` | Previous version, kept after an update for rollback. |
| `config.json` | Your configuration. Contains SMTP passwords and webhook tokens: keep it `chmod 600`. |
| `data/` | SQLite database `argos.db` (plus `-wal`/`-shm` while running). History and heartbeat only. |
| `README.md` | This file. Regenerated on every run of `install.sh`. |

## Service commands

```bash
sudo systemctl start argos
sudo systemctl stop argos
sudo systemctl restart argos
sudo systemctl status argos
sudo journalctl -u argos -f          # follow the log
sudo journalctl -u argos -n 100      # last 100 lines
```

The service is enabled and starts at boot. It restarts automatically 5 s after a crash.

## First-time configuration

Without `config.json` Argos runs in bootstrap mode: `/` answers 503 and the setup page is available.

1. Open `http://<host>:8080/setup`, create your monitors and download `config.json`.
2. Copy it to `@DIR@/config.json`, then:
   ```bash
   sudo chown @USER@ @DIR@/config.json && sudo chmod 600 @DIR@/config.json
   sudo systemctl restart argos
   ```
3. Verify: `curl -i http://127.0.0.1:8080/` answers `200`. A `503` means the configuration was
   rejected; `sudo journalctl -u argos` lists the reasons.

Every change to `config.json` needs `sudo systemctl restart argos` (no hot reload).

Argos serves plain HTTP. Put a TLS-terminating reverse proxy in front of it and set
`webHost` to `127.0.0.1` when the proxy runs on the same host.

## Update

Run the installer again in this directory:

```bash
cd @DIR@ && curl -fsSL @INSTALL_SCRIPT_URL@ | sudo bash
```

It downloads the latest release, keeps `config.json` and `data/`, moves the running jar to
`argos.jar.old` and restarts the service. The restart takes a few seconds - below the default
`heartbeatGapMinutesThreshold` of 2 minutes, so no offline alert is sent.

To change the service user during an update: `... | sudo bash -s -- --user NAME` (the user
must already exist). The unit file is rewritten on every run; put custom settings into
`/etc/systemd/system/argos.service.d/override.conf` (`sudo systemctl edit argos`) so they survive.

## Rollback

```bash
sudo systemctl stop argos
sudo cp -p @DIR@/argos.jar.old @DIR@/argos.jar
sudo systemctl start argos
```

## Backup

`data/argos.db` is a SQLite database in WAL mode. Copying the raw file while Argos runs can
produce a corrupt copy - use the SQLite backup command instead (`sudo apt install sqlite3`):

```bash
sudo sqlite3 @DIR@/data/argos.db ".backup /path/to/argos-backup.db"
```

Back up `config.json` as well. Losing the database loses the history, not the configuration.

## Uninstall

```bash
sudo systemctl disable --now argos
sudo rm /etc/systemd/system/argos.service
sudo systemctl daemon-reload
sudo rm -r @DIR@        # removes the configuration and the history as well
```

## Notes

- Ping monitors use `/usr/bin/ping` (iputils), which works for unprivileged users. Do not add
  `NoNewPrivileges=true` to the unit - it disables the binary's file capability.
- JVM flags: `--enable-native-access=ALL-UNNAMED` (sqlite-jdbc loads native code) and `-Xmx256m`.
- Health check for a proxy or an external uptime monitor: `GET /` is `200` while a valid
  configuration is loaded, `503` otherwise.
EOF
  )
  # Quoted replacements keep '&' literal even with bash 5.2's patsub_replacement.
  text=${text//@MARKER@/"$README_MARKER"}
  text=${text//@DATE@/"$date"}
  text=${text//@VERSION@/"$version"}
  text=${text//@DIR@/"$dir"}
  text=${text//@USER@/"$user"}
  text=${text//@JAVA@/"$java"}
  text=${text//@REPO@/"$REPO"}
  text=${text//@INSTALL_SCRIPT_URL@/"$INSTALL_SCRIPT_URL"}
  printf '%s\n' "$text"
}

# ---------------------------------------------------------------------------
# Main flow
# ---------------------------------------------------------------------------

main() {
  local service_user=""
  while [[ $# -gt 0 ]]; do
    case $1 in
      --user)
        if [[ $# -lt 2 || -z $2 ]]; then die "--user needs a value"; fi
        service_user=$2
        shift 2
        ;;
      --user=*)
        service_user=${1#--user=}
        if [[ -z $service_user ]]; then die "--user needs a value"; fi
        shift
        ;;
      -h|--help)
        usage
        exit 0
        ;;
      *)
        die "Unknown argument: $1 (see --help)"
        ;;
    esac
  done

  if [[ $EUID -ne 0 ]]; then
    die "Run as root:  sudo ./install.sh   or   curl -fsSL ${INSTALL_SCRIPT_URL} | sudo bash"
  fi

  # ---- prerequisites: nothing is changed before all of them pass ----
  command -v curl >/dev/null 2>&1 || die "curl not found - install it with: apt install curl"
  command -v systemctl >/dev/null 2>&1 || die "systemctl not found - this installer needs systemd"
  if [[ ! -d /run/systemd/system ]]; then
    die "systemd is not running as init on this system (no /run/systemd/system) - the service cannot be managed here"
  fi

  local java_bin java_version_output java_major
  if [[ -n ${JAVA_HOME:-} && -x ${JAVA_HOME}/bin/java ]]; then
    java_bin=${JAVA_HOME}/bin/java
  else
    java_bin=$(command -v java || true)
  fi
  if [[ -z $java_bin ]]; then
    die "java not found in root's PATH - install Java ${MIN_JAVA_MAJOR} or newer (e.g. Amazon Corretto) or point to it: sudo JAVA_HOME=/path/to/jdk ./install.sh"
  fi
  java_version_output=$("$java_bin" -version 2>&1 || true)
  java_major=$(java_major_version "$java_version_output")
  if [[ $java_major -lt $MIN_JAVA_MAJOR ]]; then
    die "Java ${MIN_JAVA_MAJOR} or newer is required, found: ${java_version_output%%$'\n'*} (${java_bin})"
  fi
  is_safe_for_unit "$java_bin" || die "Path to java contains characters that cannot be written to a unit file unquoted: ${java_bin}"

  local dir
  dir=$(pwd -P)
  if is_forbidden_dir "$dir"; then
    die "Refusing to install into ${dir}. Use a dedicated directory, e.g.: sudo mkdir -p /opt/argos && cd /opt/argos"
  fi
  is_safe_for_unit "$dir" || die "Install directory contains characters that cannot be written to a unit file unquoted (whitespace, quotes, %, ...): ${dir}"
  if [[ -e ${dir}/README.md ]] && ! grep -q -- "$README_MARKER" "${dir}/README.md"; then
    die "${dir}/README.md exists and was not written by this installer - refusing to overwrite it. Is this the right directory?"
  fi

  if [[ -z $service_user ]]; then service_user=${SUDO_USER:-root}; fi
  id -u -- "$service_user" >/dev/null 2>&1 || die "User '${service_user}' does not exist"
  is_safe_for_unit "$service_user" || die "User name contains characters that cannot be written to a unit file unquoted: ${service_user}"
  local service_group
  service_group=$(id -gn -- "$service_user")

  # ---- resolve and download the latest release ----
  log "Resolving latest release of ${REPO} ..."
  local redirect tag asset_url
  redirect=$(curl "${CURL_OPTS[@]}" --max-time 60 -o /dev/null -w '%{redirect_url}' -- "$LATEST_ASSET_URL") \
    || die "Could not resolve ${LATEST_ASSET_URL} - no release published yet, or no network access to github.com?"
  tag=$(release_tag_from_redirect "$redirect") \
    || die "Unexpected redirect for ${LATEST_ASSET_URL}: '${redirect}' (expected .../releases/download/<tag>/argos.jar) - captive portal or proxy in the way?"
  asset_url="https://github.com/${REPO}/releases/download/${tag}/argos.jar"

  trap cleanup EXIT
  TMP_JAR=$(mktemp -- "${dir}/.argos.jar.XXXXXX")
  log "Downloading ${asset_url} ..."
  curl "${CURL_OPTS[@]}" -L --max-time 600 -o "$TMP_JAR" -- "$asset_url" \
    || die "Download failed - does release ${tag} contain an asset named argos.jar?"
  if [[ ! -s $TMP_JAR ]]; then die "Downloaded file is empty"; fi
  if [[ $(head -c 2 "$TMP_JAR") != "PK" ]]; then die "Downloaded file is not a jar (zip signature missing)"; fi

  # ---- install files (config.json and data/ contents are never modified) ----
  log "Installing Argos ${tag} to ${dir} (service user: ${service_user}) ..."
  if [[ -e ${dir}/argos.jar ]]; then
    mv -f -- "${dir}/argos.jar" "${dir}/argos.jar.old"
    chown -- "${service_user}:${service_group}" "${dir}/argos.jar.old"
  fi
  chmod 644 -- "$TMP_JAR"
  chown -- "${service_user}:${service_group}" "$TMP_JAR"
  mv -f -- "$TMP_JAR" "${dir}/argos.jar"
  TMP_JAR=""

  mkdir -p -- "${dir}/data"
  chown -R -- "${service_user}:${service_group}" "${dir}/data"
  chmod 750 -- "${dir}/data"
  if [[ -e ${dir}/config.json ]]; then
    chown -- "${service_user}:${service_group}" "${dir}/config.json"
    chmod 600 -- "${dir}/config.json"
  fi

  render_readme "$dir" "$service_user" "$tag" "$(date -u '+%Y-%m-%d %H:%M UTC')" "$java_bin" > "${dir}/README.md"
  chown -- "${service_user}:${service_group}" "${dir}/README.md"
  chmod 644 -- "${dir}/README.md"

  # ---- systemd ----
  log "Writing ${UNIT_PATH} and (re)starting the service ..."
  render_unit "$dir" "$service_user" "$java_bin" > "$UNIT_PATH"
  chmod 644 -- "$UNIT_PATH"
  systemctl daemon-reload
  systemctl enable --quiet "$UNIT_NAME"
  systemctl restart "$UNIT_NAME"
  sleep 3
  if ! systemctl is-active --quiet "$UNIT_NAME"; then
    journalctl -u "$UNIT_NAME" -n 30 --no-pager >&2 || true
    if [[ -e ${dir}/argos.jar.old ]]; then
      printf 'Rollback: sudo systemctl stop argos && sudo cp -p %s/argos.jar.old %s/argos.jar && sudo systemctl start argos\n' "$dir" "$dir" >&2
    fi
    die "${UNIT_NAME} is not running - see the log above (sudo journalctl -u argos)"
  fi

  # ---- summary ----
  local host_ip
  host_ip=$(hostname -I 2>/dev/null | awk '{print $1}' || true)
  log ""
  log "Argos ${tag} is installed and running."
  log "  Directory : ${dir}"
  log "  Service   : sudo systemctl status argos   |   sudo journalctl -u argos -f"
  log "  README    : ${dir}/README.md"
  if [[ ! -e ${dir}/config.json ]]; then
    log ""
    log "No config.json yet - Argos runs in bootstrap mode."
    log "  1. Open http://${host_ip:-<host>}:8080/setup and create your monitors, download config.json"
    log "  2. Copy it to ${dir}/config.json  (sudo chown ${service_user} ...; sudo chmod 600 ...)"
    log "  3. sudo systemctl restart argos"
  fi
}

# Run when executed directly or piped into bash; not when sourced (tests).
# stdin is redirected so no child process can consume the script while it streams from curl.
if [[ -z ${BASH_SOURCE[0]:-} || ${BASH_SOURCE[0]} == "$0" ]]; then
  main "$@" </dev/null
fi
